### PR TITLE
Backport "Coalescing the Gateway.spec.servers[]" #67 to the 0.14 branch

### PR DESCRIPTION
**Pull request by mhenke1**
This PR ports the changes from #67 back to the 0.14 branch to make the performance improvements available in Knative 0.14.x

### CODE REVIEW

**Comment by mhenke1** [comment]
I consent

**Comment by mhenke1** [comment]
/assign @mattmoor 
Please see my question above about the right way to put this into a Knative 0.14.x release.

**Comment by markusthoemmes** [comment]
Looks just about okay.

/assign @JRBANCEL 
/ok-to-test

Welcome @mhenke1 :wave:

**Comment by mhenke1** [comment]
The tests are failing since there is no is no 
`net-istio/vendor/knative.dev/serving/test/test_images/helloworld/` image in 0.14 
Confusingly I do not see this referenced by this PR. 
Investigating.

**Comment by tcnghia** [comment]
@mhenke1 this may be due to a `ko` upgrade

**Comment by tcnghia** [comment]
ah, no the image is really missing https://github.com/knative/net-istio/tree/release-0.14/vendor/knative.dev/serving/test/test_images  

I think we'll need to fix the build for release-0.14 first, probably by adding the image into here https://github.com/knative/net-istio/blob/release-0.14/Gopkg.toml#L12 and rerun `./hack/update-deps.sh`.

**Comment by markusthoemmes** [comment]
@JRBANCEL you'll have to leave the "@googlebot I consent" thingy.

**Comment by JRBANCEL** [comment]
@googlebot I consent.

**Comment by mhenke1** [comment]
changing the toml file and running ./hack/update-deps.sh added much more than the missing image. I feel unsure to push all those changes now. I will need some time to investigate and judge.

**Comment by markusthoemmes** [comment]
It vendored some backports. Those look fine to me.

**Comment by mhenke1** [comment]
Cleaned up and run it again. This time it looks good. 
I probably had some leftovers from running the update script when having deleted the lock file in one of my runs.

**Comment by tcnghia** [comment]
The upload-test-images.sh only upload images if the directory existed.

So I am still confused why it is trying helloworld at all.

**Comment by markusthoemmes** [comment]
@tcnghia I bet it's because the proxy image specifies the helloworld image as a target in it's service definition. I forgot to fix that on serving master. It hit us in other places too.

**Comment by markusthoemmes** [comment]
https://github.com/knative/serving/pull/8124 for the upstream change.

**Pull request merged**
