### PR TITLE
Update go.mod to specify the module is go1.14 & use vendored ingress conformance tests

### PR DESCRIPTION
**Pull request by dprotaso**
Thus the go commands will default to -mod=vendor

See: https://golang.org/doc/go1.14#go-command

### CODE REVIEW

**Comment by tcnghia** [comment]
This won't work yet due to test vendoring

**Comment by tcnghia** [comment]
See https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_net-istio/123/pull-knative-net-istio-integration-tests/1266492338197237761

**Comment by dprotaso** [comment]
Yeah I noticed it here: https://github.com/knative/net-http01/pull/30

**Pull request merged**
