### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign tcnghia
/cc tcnghia

### CODE REVIEW

**Comment by vagababov** [comment]
/cc @tcnghia @ZhiminXiang @mattmoor 
This fails most of the UTs.

**Comment by ZhiminXiang** [comment]
I sent out a PR https://github.com/knative/net-istio/pull/161 with the unit test fix. So I am gonna close this one.

**Pull request closed without merging**
