### PR TITLE
Move wildcard gateway reconciliation out of the Istio Ingress Gateway loop 

### PR DESCRIPTION
**Pull request by ZhiminXiang**
When creating wildcard gateways, we already traverse Istio Gateway service: https://github.com/knative/net-istio/blob/master/pkg/reconciler/ingress/resources/gateway.go#L126

Therefore, there is no need to put them under the loop again.

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm
/hold

This change should be merged after v0.16 released? If we should merge it before the release, please feel free to unhold @tcnghia @ZhiminXiang

**Comment by ZhiminXiang** [comment]
> /lgtm
> /hold
> 
> This change should be merged after v0.16 released? If we should merge it before the release, please feel free to unhold @tcnghia @ZhiminXiang

Good call. It should be merged after v0.16.

**Comment by ZhiminXiang** [comment]
/unhold
release is cut.

**Pull request merged**
