### PR TITLE
Add an `--upgrade` flag to `./hack/update-deps.sh`

### PR DESCRIPTION
**Pull request by mattmoor**
/assign n3wscott

### CODE REVIEW

**Comment by n3wscott** [comment]
Failure:

```
dirname: missing operand
Try 'dirname --help' for more information.
---------------------------------------------------
---- Checking autogenerated code is up-to-date ----
---------------------------------------------------
---- Mon Mar  2 13:23:14 PST 2020
---------------------------------------------------
cp: cannot stat '/home/prow/go/src/knative.dev/net-istio/pkg': No such file or directory
```

**Comment by mattmoor** [comment]
Yeah, this probably can't land until this repo has code

**Pull request merged**
